#!/bin/bash

echo "❦ Font Revealer for Adobe Creative Cloud ❦"

echo "Dry-Run will preview the renaming process without copy any files."
select dce in "Dry-Run" "Copy" "Exit"; do
    case $dce in
        Dry-Run ) isDry=true; echo "Dry-running..."; break;;
        Copy ) isDry=false; echo "Copy & rename files..."; break;;
        Exit ) exit;;
    esac
done

cd ~/Library/Application\ Support/Adobe/CoreSync/plugins/livetype/
# grab all otf dot files (adjust to your needs)
find . -type f -iname "*.otf" | while read file
do
  # the "Postscript name:" does not contain spaces. good for file names.
  postscriptName=`otfinfo -p ${file}`
  
  if [ "$isDry" = false ] ; then
    # create a Fonts dir within downloads, if there is none
    mkdir -p ~/Downloads/Fonts/
    # copy files (if no dry-run)
    cp $file ~/Downloads/Fonts/$postscriptName.otf
  fi

  # echo changes:
  echo "$file\t⮕\t$postscriptName.otf"
done

echo "🚀 DONE! Check your 'Fonts' directory within Downloads if you selected Option 2 (Copy)".
